[{
    "collection": {
        "items": {
            "LuklaVillage": {
                "id": "LuklaVillage",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Lukla Village "
            },
            "JorsalleVillage": {
                "id": "JorsalleVillage",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Jorsalle Village "
            },
            "NamcheVillage": {
                "id": "NamcheVillage",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Namche"
            },
            "NamcheBazaar": {
                "id": "NamcheBazaar",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Namche Bazaar"
            },
            "AboveKunde": {
                "id": "AboveKunde",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Kunde"
            },
            "AboveKhmjng": {
                "id": "AboveKhmjng",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Khumjung"
            },
            "Thyangboche": {
                "id": "Thyangboche",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Thyangboche"
            },
            "ThyangbocheACU": {
                "id": "ThyangbocheACU",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Thyangboche"
            },
            "ThyangbocheGCU": {
                "id": "ThyangbocheGCU",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Thyangboche"
            },
            "Pangboche": {
                "id": "Pangboche",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Pangboche"
            },
            "PherDingb": {
                "id": "PherDingb",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Periche & Dingboche"
            },
            "AbovePherDingb": {
                "id": "AbovePherDingb",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Periche & Dingboche"
            },
            "TermKhuGl": {
                "id": "TermKhuGl",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Khumbu Glacier Terminus"
            },
            "Lbche": {
                "id": "Lbche",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Lubche"
            },
            "GorShep": {
                "id": "GorShep",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Gorak Shep"
            },
            "AboveKP": {
                "id": "AboveKP",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Khumbu Glacier"
            },
            "GrkShpAngLamu": {
                "id": "GrkShpAngLamu",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "AngLamo Lodge"
            },
            "ABC": {
                "id": "ABC",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Advanced Base Camp"
            },
            "ABCPumori": {
                "id": "ABCPumori",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Advanced Base Camp"
            },
            "AboveIceFall1": {
                "id": "AboveIceFall1",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Khumbu Ice Fall"
            },
            "AboveIceFall2": {
                "id": "AboveIceFall2",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Advanced Base Camp"
            },
            "EntWCwm": {
                "id": "EntWCwm",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Western Cwm"
            },
            "EAH_ABC": {
                "id": "EAH_ABC",
                "layout_X": 0.0,
                "layout_Y": 0.0,
                "layout_HEIGHT": 0.0,
                "layout_WIDTH": 0.0,
                "embeddingType": "Global",
                "contentType": "TextOverlays",
                "artifactTypeId": "TextOverlayVisual",
                "artifactRenderStyle": "TextTitles",
                "fontColor": "#FFFFFFFF",
                "title": "Advanced Base Camp"
            }
        },
        "layout": {
            "groups": []
        }
    }
}]